### ISSUE TITLE
Surname is never returned by #retrieveUserDetails method

### ISSUE THREAD

**Issue by geek-soft** [hmcts/idam-java-client#40]
### What would you like to change?

Since release of 1.2.0 `IdamApi#retrieveUserDetails` does not return user surname.

Most likely `@JsonIgnore` in the following place is the issue: https://github.com/hmcts/idam-java-client/pull/36/files#diff-050d7fc39b75312fa3594f44bf35bb67R43.

### How do you think that would improve the project?

Surname should not be excluded.

### If this entry is related to a bug, please provide the steps to reproduce it

Call `IdamApi#retrieveUserDetails` to retrieve details of an existing user that has surname set.

**Comment by alexwakeman** [comment]
Hi @geek-soft - this has been fixed here: https://github.com/hmcts/idam-java-client/pull/43
